services:
  flight:
    build:
      context: ./atomicMicroservices/flightService
      dockerfile: Dockerfile
    image: edrictan/flight:1.0
    container_name: flight
    ports:
      - "5000:5000"
    env_file: #env_file directive automatically loads the environment variables from the .env
      - .env # This loads the variables from .env file
  # networks:
  #   - flight-network

  seat:
    build:
      context: ./atomicMicroservices/seatService
      dockerfile: Dockerfile
    image: edrictan/seat:1.0
    container_name: seat
    ports:
      - "8080:8080"
    # environment:
    #   - dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/book # set in example/resources/application.properties
