CREATE DATABASE IF NOT EXISTS `seat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `seat`;

DROP TABLE IF EXISTS `seat`;
CREATE TABLE IF NOT EXISTS seat (
    flightID INT NOT NULL,
    seatID VARCHAR(10) NOT NULL,
    availability BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (flightID, seatID)
);

-- For Flight 1 (New York -> London, 01-04-2025)
INSERT INTO seat (flightID, seatID, availability) VALUES
(1, '1A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '1B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '1C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '1D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '1E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '1F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '2F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '3F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '4F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '5F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '6F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '7F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '8F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '9F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '10F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '11F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '12F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '13F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '14F', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15A', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15B', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15C', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15D', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15E', IF(RAND() < 0.5,TRUE, FALSE)),
(1, '15F', IF(RAND() < 0.5,TRUE, FALSE));